### ISSUE TITLE
Mail from Uhl

### ISSUE THREAD

**Issue by m-langer** [AIS-22/UNI-AIS-MediaDataFormats#77]
@AIS-22/mediadata 
Points two be cleared from the mail:

- [x] #80
- [x] #82
- [x] schlage vor das in 2 plots zu teilen; der erste zeigt alle mit transfer-rearning; der zweite zeigt transfer learning 10, 25, 40, 100 sowie mixed self-trained und mixed pre-trained; bitte mit farben aufpassen - besonders die mit blau kennt man fast nicht auseinander (5 und mixed) ....... Wird in Verbindung mit #82 erledigt
- [x]  ich finde die confusion plots nicht ! #87
- [x] #84
- [x] #83
- [x]  bei JXR gibts ja 3 varianten (wohl je nach verwendung der POT) - bitte im text erklären! wird in Verbindung mit #83 erledigt 
- [x]  die PSNR/SSIM plots beinhalten nur eine jxr - variante - warum ?
- [x] #81
- [x] Remove images in paper folder (should be already in project dir)

**Comment by m-langer** [comment]
Regarding Font size for PSNR/SSIM I would suggest 23
